### ISSUE TITLE
Error in mclapply(levels(fac.block), function(lev) x[, which(fac.block == :  'mc.cores' > 1 is not supported on Windows)

### ISSUE THREAD

**Issue by SofiaDe** [thibautjombart/adegenet#140] opened 2016-04-11 14:14 UTC
Help!! I can`t run the function table(pop(GL), grp$grp) and the function dapc1<- dapc(GL, grp$grp) (error: Error in mclapply(levels(fac.block), function(lev) x[, which(fac.block ==  : 
  'mc.cores' > 1 is not supported on Windows). How can I fix them???

Thanks

**Comment by thibautjombart** [comment] 2016-04-13 10:04
Hi Sofia,
I think the issue is related to #109 and #126 which have been fixed in the current github version of adegenet. 

The first error is different, but you need to give us more context and ideally a reproducible example. Typically the error will be that `pop(GL)` or `grp$grp` is not what you think (NULL, or object missing, etc.). So that would be the first thing to check

**Comment by SofiaDe** [comment] 2016-04-18 13:17
Thank for your answer, I could solve these problems. But I have another questions: 
How is max.n.clust defined?
How ploidy is defined if I have diploid and tetraploid individuals into the same dataset?

**Comment by thibautjombart** [comment] 2016-04-18 14:16
Hi Sofia, 
these are different topics, and not exactly 'issues' - probably best discussed on the forum:
http://lists.r-forge.r-project.org/mailman/listinfo/adegenet-forum

**Closed by thibautjombart** 2016-04-18 14:16 UTC
