### ISSUE TITLE
Error message with read.PLINK and extract.PLINKmap

### ISSUE THREAD

**Issue by kalligood** [thibautjombart/adegenet#94] opened 2015-10-09 18:51 UTC
Hi,
I am having trouble importing my data into adegenet using the read.PLINK command.  I have converted my data into a plink.raw file using --recodeA but am getting an error when I try to load my data:

> MIplink <- read.PLINK("plink.raw")
> 
> Reading PLINK raw format into a genlight object... 
> Reading loci information... 
> Reading and converting genotypes... 
> .Error in (function (classes, fdef, mtable)  : 
>  unable to find an inherited method for function ‘nLoc’ for signature ‘"try-error"’
> In addition: Warning message:
> In mclapply(txt, function(e) new("SNPbin", snp = e, ploidy = 2),  :
>  1 function calls resulted in an error

I am also having trouble using the extract.PLINKmap command and get this error:

> Pmap <- extract.PLINKmap("batch_1.plink.map")
> 
> Error in factor(txt[ord, 1]) : object 'ord' not found
> In addition: Warning message:
> In matrix(txt, ncol = 4, byrow = TRUE) :
>  data length [3997] is not a sub-multiple or multiple of the number of rows [1000]

I will send you a link to a dropbox with the data in an email.  I'm new to github, so I'm not sure if this is exactly how you would like me to document my data and code.  
Thanks for your time!

Best,
Kristin

**Comment by thibautjombart** [comment] 2015-10-14 16:33
Right, I have to work from a crippled windows computer so things are slow and I can't make as many tests as I'd like.. but issue should be partly fixed as of 798e4766e5668ff5c55ea506d0ab8966e625f65b.

I still get an error for the map but now I can read data in fine:
```r
> x=read.PLINK("plink.raw", paralle=FALSE)

 Reading PLINK raw format into a genlight object... 


 Reading loci information... 

 Reading and converting genotypes... 
.
 Building final object... 

...done.

> x
 /// GENLIGHT OBJECT /////////

 // 478 genotypes,  999 binary SNPs, size: 955.1 Kb
 19174 (4.02 %) missing data

 // Basic content
   @gen: list of 478 SNPbin
   @ploidy: ploidy of each individual  (range: 2-2)

 // Optional content
   @ind.names:  478 individual labels
   @loc.names:  999 locus labels
   @pop: population of each individual (group size range: 24-84)
   @other: a list containing: sex  phenotype  pat  mat 

```

**Comment by omgmvi** [comment] 2016-03-30 19:28
In case it is not solved, I had same issue with the funcion extract.PLINKmap
In my case, my file .map was created by PLINK before I created the .raw.
.map was space separated file so I need to change each ´space´for \t using regular expressions
the problem with ord came when the file .raw had headers like 1:234_C but the map was more like 1:234
My solution was to change the line
ord <- match(locNames(x), txt[, 2])
for 
ord <- match(do.call(rbind,strsplit(locNames(x),split = "_"))[,1],txt[,2])

Sorry if this has been already solved.

**Comment by thibautjombart** [comment] 2016-03-31 15:12
I think I left it where it was as I didn't get confirmation for the last partial fix. 
Can you post a reproducible minimal example?

**Comment by omgmvi** [comment] 2016-04-01 10:43
Let's try.
I have .ped and .maps files that looks like follows:
.ped (space separated values, 10 snps 2 alleles)
6909 6909 0 0 0 0 C C A A C C C C T T T T T T T T T T A A
6977 6977 0 0 0 0 C C A A C C C C T T C C C C T T T T A A
100000 100000 0 0 0 0 C C G G C C C C T T T T T T T T T T G G

.map (space separated values)
1 1:657 0 657
1 1:3102 0 3102
1 1:4648 0 4648

. raw after /plink -ped file.ped -map file.map -recodeA
(still, space separated values)
FID IID PAT MAT SEX PHENOTYPE 1:657_T 1:3102_G 1:4648_A
6909 6909 0 0 0 -9 0 0 0
6977 6977 0 0 0 -9 0 0 0

Then, alleles at .map and alleles at .raw do not coincide when extractPLINKmap executes
ord <- match(locNames(x), txt[, 2])
because there is no match. So I modified it to cut the minor alllele after '_'

Thanks for your quick comment! Odin

**Comment by tjsmyser** [comment] 2017-08-01 15:23
Thibaut,

I am reading through the comments above, as I am encountering the same problems, but I do not seem to understand the solution.  I am working with HD SNP data generated from a commercial Illumina bead array.  I have successfully imported my genotypes into adegenet by first converting my *.ped and *.map files in PLINK, exporting a *.raw file, and then importing the *.raw file (code listed below) into adegenet.

a = read.PLINK("ASM_RefSet_RAW.raw", parallel = FALSE) 

I seem to be unable to import the corresponding chromosome and position information.  I have attempted to use the following code without success.  Any suggestions you may have would greatly be appreciated.

a = read.PLINK("ASM_RefSet_RAW.raw", parallel = FALSE, map.file = "ASM_RefSet_RAW.map")

Error message received = 
Warning message:
In matrix(txt, ncol = 4, byrow = TRUE) :
  data length [29375] is not a sub-multiple or multiple of the number of rows [7344]

I have also tried:

chr_position = extract.PLINKmap("ASM_RefSet_RAW.map")

Error message received = 
Error in factor(txt[ord, 1]) : object 'ord' not found
In addition: Warning message:
In matrix(txt, ncol = 4, byrow = TRUE) :
  data length [29375] is not a sub-multiple or multiple of the number of rows [7344]

I also imported my *.map file into PLINK and then exported the *.map file with --recode.  The following code appear to work with no error messages returned, yet when I query the chromosome information with “ head(other(a),100) ” R returns $ chromosome <NA>…, and $position <NA>…
Again, any suggestions you may have would be greatly appreciated,
Tim

**Comment by tjsmyser** [comment] 2017-08-01 15:52
Sorry, I forgot to add that last bit of code.  Below is the code in which I am reading in the exported *.map file from PLINK with no error message returned:

a = read.PLINK("ASM_RefSet_RAW.raw", parallel = FALSE, map.file = "MAP.map")

**Comment by thibautjombart** [comment] 2017-08-18 11:19
Should be fixed via 4992cfa0f91a56f5b28ba84b168bbb3ebd7fb630

@tjsmyser can you install the current devel and check?

**Comment by thibautjombart** [comment] 2017-08-29 09:05
Poke @tjsmyser @omgmvi  - lemme know if the issue is fixed ;)

**Comment by omgmvi** [comment] 2017-08-29 10:48
Sorry, I wish i can, but I have no access no my data for a time. Hopefully
other users can be more useful. Thanks for your time and effort!

2017-08-29 10:05 GMT+01:00 Thibaut Jombart <notifications@github.com>:

**Comment by tjsmyser** [comment] 2017-09-14 20:02
Thibaut,

Sorry for the long delay.  I got pulled away from this analysis and it took me a while to get back to it.  I ran it yesterday and it ran smoothly.  Thanks so much for your help!

Tim

**Comment by thibautjombart** [comment] 2017-09-15 16:18
Sweet!

**Closed by thibautjombart** 2017-09-15 16:18 UTC
