### ISSUE TITLE
import2genind() taking very long

### ISSUE THREAD

**Issue by cryptic0** [thibautjombart/adegenet#47] opened 2015-04-20 11:06 UTC
R version 3.1.1
Adegenet version 2.0.0 

The import2genind('input.stru') is taking too long on big data sets.  For example, one of my data set has 94K markers and 242 individuals.  This file is being converted to genind since yesterday morning and it still not has finished.  I tried this on two computers with same result.  The data file itself seems ok because STRUCTURE runs fine on it.

I am happy to provide further information.  Thanks.

**Comment by thibautjombart** [comment] 2015-04-20 11:19
Thanks for the report. Can you send us a toy example (data+code) to reproduce the issue? Benchmarking suggested so far that the new method was up to 3 times faster (eHGDP data).

**Comment by cryptic0** [comment] 2015-04-20 11:22
I should mention that this function works fine on smaller data sets.  It took, for example, less than 30 seconds to import a structure file with 2040 markers and 156 individuals.  I can send the files I have problem with, but they are too big (90Mb+).

**Comment by thibautjombart** [comment] 2015-04-20 11:26
Makes sense, but unless you have a reproducible example there is little we can do beside speculating. 
At least we need to show that the version of df2genind is slower on some large datasets, then we can figure out how to fix the issue.

Can you check what the status of your RAM is? If your RAM is saturated, then the HD is used and things will take forever.

**Comment by cryptic0** [comment] 2015-04-20 11:28
I will make arrangements to send the data file to you today.  My institution has a file transfer service.

RAM Status (in Gb):
             total       used       free     shared    buffers     cached
Mem:            62         17         44          0          0          3
-/+ buffers/cache:         13         49
Swap:            7          0          7

**Comment by thibautjombart** [comment] 2015-04-20 12:31
Great! Just post the url here when you have it. Thanks!

**Comment by thibautjombart** [comment] 2017-05-09 12:31
I am currently reviewing old issues. Is this still relevant?

**Comment by Oxalis** [comment] 2017-06-09 16:15
Hi, 

Maybe I am too late but I am trying to use df2genind on a vcf that is ~360,000 SNPs from 12 individuals and it has been running for several hours already. If there is a way to have this goes quicker that would be great! Thanks!

**Comment by knausb** [comment] 2017-06-09 16:31
This appears to be a different topic from the original post involving ` import2genind('input.stru')`. But I saw it and feel I may have something to contribute. I've placed some documentation on memory use [here](https://knausb.github.io/vcfR_documentation/how_much_memory.html). Its presented as relevant to vcfR objects, but you can see the example as a matrix with 10 columns and as many rows as you have variants. According to the plot you should need about  6.4 Gb of RAM to hold 100,000 variants. You report you are working with 360,000 variants. Have you exceeded the amount of physical RAM you have and are now using swap/virtual RAM? If so, that's your issue.

**Comment by thibautjombart** [comment] 2017-06-12 10:39
Thanks @knausb for the thoughts on RAM use. I've never used *memuse*, naively I would look at:
```
> x <- matrix(integer(1), ncol = 1e6, nrow = 50)
> print(object.size(x), unit = "auto")
190.7 Mb
```
which would be the approximate size of a *genind* with 500,000 biallelic SNPs (well, that'd be the `@tab` slot only, but that's the bulk of it). So it looks like RAM shouldn't be an issue here, but this is of course very different from the memory used by the function during conversion by `df2genind`. Any take on that? @zkamvar @romunov @caitiecollins I can't remember if you profiled this function at some point?

**Comment by zkamvar** [comment] 2017-06-12 14:28
@thibautjombart's assessment of the memory usage is correct (but should be considered a lower bound as VCF format can contain non-SNP variants). In @knausb's vignette, the `as.numeric()` method [converts the values to bytes by default](https://www.rdocumentation.org/packages/memuse/versions/3.0-1/topics/Converters). 

@Oxalis mentions that they are trying to import data from a VCF file. Is the data frame oriented correctly? By default, VCF stores variants in rows and samples in columns. Most population genetic software is oriented in the opposite way. 

You may want to consider using @knausb's package to read in your vcf file (`read.vcf()`) and export it to a genind with `vcfR2genind()`.

**Comment by knausb** [comment] 2017-06-12 16:44
Oops, that actually revealed an error in my math. Should be fixed now. However, I notice a slight discrepancy still. If you have the forethought, as @thibautjombart had, to force your matrix to be integers the above is correct. If you let R handle it you'll get numerics, which will cost you a little more RAM.

```
> x <- matrix(1, ncol = 1e6, nrow = 50)
> print(object.size(x), unit = "auto")
381.5 Mb
```

which now agrees with

```
>  howbig(nrow=1e6, ncol=50)
381.470 MiB
```

Incidently, `vcfR::vcfR2genind()` calls `adegenet::df2genind()`. So if that is the issue then you will not circumvent the issue this way. However, `vcfR::vcfR2genind()` will transform your data for you.

Thanks!

**Comment by ljaudi** [comment] 2018-05-07 03:39
Hi, i have 300 individuals and 74723 loci. Should I be worried that this conversion is taking a really long time?  I am worried I don't have enough memory on my computer to input this dataset.

**Comment by KlausVigo** [comment] 2020-01-20 11:31
@zkamvar and @knausb, 
the improvements to `adegenet::df2genind()`  0c9dc83 and 33b8d0c (pull request #260) will improve also `vcfR::vcfR2genind()`. This transformation is now much faster and uses less memory. We had memory problems using `vcfR::vcfR2genind()`, that's why I tackled it to begin with. So this issue might be closed for now. 
Klaus

**Comment by zkamvar** [comment] 2020-01-20 13:55
@KlausVigo, you are a peach! Thank you. 

This version of adegenet is in submission to CRAN, though I suspect it won't be available until next week because they will find something to nitpick (my guess is that there will be no DOIs present). If you want to watch the drama unfold, I have a PR open in #268

**Closed** 2020-01-22 16:14 UTC
