### ISSUE TITLE
read.genepop unused argument issue

### ISSUE THREAD

**Issue by Jamiesells** [thibautjombart/adegenet#113] opened 2015-12-02 17:17 UTC
Apologies if this has been covered - My R knowledge is on a slow up word trajectory, so not sure if a bug or error on my part.

I'm trying to bring in a .gen file  using command 
`r1r2remrem2<-read.genepop("home/jt358/Desktop/rem.gen", missing="0000")`. The file will only convert to a genind  object if I leave out the missing argument.

The error I get is 
```r
r1r2remrem2<-read.genepop("home/jt358/Desktop/rem.gen", missing="0000") 
Error in read.genepop("home/jt358/Desktop/rem.gen", missing = "0000") : 
  unused argument (missing = "0000")
```

If I don't include the missing arguement, then when identifying missing data further on using
```r
missing <-info_table(r1r2remrem2,type=c("missing"), percent=TRUE,  plot=TRUE, df=TRUE, returnplot=TRUE, low="white", high="red", plotlab=F, scaled=FALSE)
``` 
I get 'no missing data found!', when there was missing data in the .gen file labelled as 0000

I'm using adegenet  2.0.0 and have R version   3.2.2 (2015-08-14) -- "Fire Safety"

Many thanks for any info

**Comment by thierrygosselin** [comment] 2015-12-02 17:32
Funny coincidence, I'm currently testing the same thing.
The bug is observed in all the functions that depends on df2genind.
In my case if I specify NA character, on large dataset, the function keeps calculating forever.
Without the NA, then, the missings are considered like values.

I think it's a v.2 only bug.
I'll have something reproducible later today.
Thierry

**Comment by Jamiesells** [comment] 2015-12-02 17:36
Many thanks for such a swift reply Thierry - I'll look forward to what you come up with :)

**Comment by romunov** [comment] 2015-12-02 20:30
Can you guys try it out with the bleeding edge version from github? Also, a reproducible example would go a long way.

**Comment by thierrygosselin** [comment] 2015-12-03 19:47
see my separate post

**Comment by thibautjombart** [comment] 2015-12-03 22:29
There is no longer a `missing` argument since 2.0.0. 
I am closing this thread and following up on:
https://github.com/thibautjombart/adegenet/issues/114

**Closed by thibautjombart** 2015-12-03 22:29 UTC
